/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as DailyUpdateRouteImport } from './routes/daily-update'
import { Route as CaseHistoryRouteImport } from './routes/case-history'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDailyUpdateRouteImport } from './routes/api/public/daily-update'
import { Route as ApiPublicCaseHistoryRouteImport } from './routes/api/public/case-history'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyUpdateRoute = DailyUpdateRouteImport.update({
  id: '/daily-update',
  path: '/daily-update',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseHistoryRoute = CaseHistoryRouteImport.update({
  id: '/case-history',
  path: '/case-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyUpdateRoute = ApiPublicDailyUpdateRouteImport.update({
  id: '/api/public/daily-update',
  path: '/api/public/daily-update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaseHistoryRoute = ApiPublicCaseHistoryRouteImport.update({
  id: '/api/public/case-history',
  path: '/api/public/case-history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-history': typeof CaseHistoryRoute
  '/daily-update': typeof DailyUpdateRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/public/case-history': typeof ApiPublicCaseHistoryRoute
  '/api/public/daily-update': typeof ApiPublicDailyUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-history': typeof CaseHistoryRoute
  '/daily-update': typeof DailyUpdateRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/public/case-history': typeof ApiPublicCaseHistoryRoute
  '/api/public/daily-update': typeof ApiPublicDailyUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-history': typeof CaseHistoryRoute
  '/daily-update': typeof DailyUpdateRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/public/case-history': typeof ApiPublicCaseHistoryRoute
  '/api/public/daily-update': typeof ApiPublicDailyUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-history'
    | '/daily-update'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/api/public/case-history'
    | '/api/public/daily-update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-history'
    | '/daily-update'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/api/public/case-history'
    | '/api/public/daily-update'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-history'
    | '/daily-update'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/api/public/case-history'
    | '/api/public/daily-update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseHistoryRoute: typeof CaseHistoryRoute
  DailyUpdateRoute: typeof DailyUpdateRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ApiPublicCaseHistoryRoute: typeof ApiPublicCaseHistoryRoute
  ApiPublicDailyUpdateRoute: typeof ApiPublicDailyUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-update': {
      id: '/daily-update'
      path: '/daily-update'
      fullPath: '/daily-update'
      preLoaderRoute: typeof DailyUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-history': {
      id: '/case-history'
      path: '/case-history'
      fullPath: '/case-history'
      preLoaderRoute: typeof CaseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-update': {
      id: '/api/public/daily-update'
      path: '/api/public/daily-update'
      fullPath: '/api/public/daily-update'
      preLoaderRoute: typeof ApiPublicDailyUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/case-history': {
      id: '/api/public/case-history'
      path: '/api/public/case-history'
      fullPath: '/api/public/case-history'
      preLoaderRoute: typeof ApiPublicCaseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseHistoryRoute: CaseHistoryRoute,
  DailyUpdateRoute: DailyUpdateRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  ApiPublicCaseHistoryRoute: ApiPublicCaseHistoryRoute,
  ApiPublicDailyUpdateRoute: ApiPublicDailyUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
